const paths = {
    PUBLIC: "/",
    HOME: "",
    MOVIE: "movie",
    img: (type, url) => `https://image.tmdb.org/t/p/${type}/${url}`,
    video: (url) => `https://www.youtube.com/embed/${url}`,
    NOW_PLAYING: "now-playing",
    POPULAR: "popular",
    UP_COMING: "upcoming",
    TV: "tv",
    AIRING_TODAY: "airing-today",
    TOP_RATED: "top-rated",
    PEOPLE: "people",
    ALL: "",
    SEARCH: "search",
    detail: (type, id, title) => `/${type}/${id}/${title}`,
    detailPerson: (type, id) => `/${type}/${id}`,
    DETAIL_MOVIE: "movie/:movie_id/:title",
    DETAIL_TV: "tv/:tv_id/:title",
    DETAIL_PERSON: "person/:person_id",
};
export default paths;
